# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            brkpnt.
tagline:          "Where I'm At"
description:      'A modest collection of <strong>code</strong>, tutorials and <strong>lessons learned</strong> regarding <strong>HPC and the modern web</strong>.'
url:              http://zebulasampedro.github.io/
baseurl:          /

author:
  name:           'Zebula Sampedro'
  url:            https://github.com/ResearchComputing

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zebulasampedro/zebulasampedro.github.io
